[INFO   ] Logger: Record log in /storage/emulated/0/Documents/Pydroid3/.kivy/logs/kivy_24-08-15_29.txt
[INFO   ] Kivy: v2.2.1
[INFO   ] Kivy: Installed at "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.11/site-packages/kivy/__init__.py"
[INFO   ] Python: v3.11.4 (main, Sep 30 2023, 10:54:38) [GCC 11.4.0]
[INFO   ] Python: Interpreter at "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/bin/python3"
[INFO   ] Logger: Purge log fired. Processing...
[INFO   ] Logger: Purge finished!
[INFO   ] Factory: 190 symbols loaded
[INFO   ] Image: Providers: img_tex, img_dds, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] Text: Provider: sdl2
[INFO   ] Window: Provider: sdl2
[INFO   ] GL: Using the "OpenGL ES 2" graphics system
[INFO   ] GL: Backend used <sdl2>
[INFO   ] GL: OpenGL version <b'OpenGL ES 3.2 v1.r34p0-01eac0.647697edc2c1e52dec0a7e587b626ab2'>
[INFO   ] GL: OpenGL vendor <b'ARM'>
[INFO   ] GL: OpenGL renderer <b'Mali-G57'>
[INFO   ] GL: OpenGL parsed version: 3, 2
[INFO   ] GL: Texture max size <16383>
[INFO   ] GL: Texture max units <128>
[INFO   ] Window: auto add sdl2 input provider
[INFO   ] Window: virtual keyboard not allowed, single mode, not docked
[WARNING] stderr: Traceback (most recent call last):
[WARNING] stderr:   File "kivy/properties.pyx", line 2229, in kivy.properties.ColorProperty.convert
[WARNING] stderr:   File "kivy/properties.pyx", line 2240, in kivy.properties.ColorProperty.parse_str
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.11/site-packages/kivy/utils.py", line 120, in get_color_from_hex
[WARNING] stderr:     value = [int(x, 16) / 255.
[WARNING] stderr:             ^^^^^^^^^^^^^^^^^^
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.11/site-packages/kivy/utils.py", line 120, in <listcomp>
[WARNING] stderr:     value = [int(x, 16) / 255.
[WARNING] stderr:              ^^^^^^^^^^
[WARNING] stderr: ValueError: invalid literal for int() with base 16: 'r'
[WARNING] stderr: 
[WARNING] stderr: The above exception was the direct cause of the following exception:
[WARNING] stderr: 
[WARNING] stderr: Traceback (most recent call last):
[WARNING] stderr:   File "/storage/emulated/0/Documents/Pydroid3/Stop Watch.py", line 55, in <module>
[WARNING] stderr:     StopwatchApp().run()
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.11/site-packages/kivy/app.py", line 955, in run
[WARNING] stderr:     self._run_prepare()
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.11/site-packages/kivy/app.py", line 925, in _run_prepare
[WARNING] stderr:     root = self.build()
[WARNING] stderr:            ^^^^^^^^^^^^
[WARNING] stderr:   File "/storage/emulated/0/Documents/Pydroid3/Stop Watch.py", line 23, in build
[WARNING] stderr:     stop_btn = Button(text="Stop", on_press=self.stop)
[WARNING] stderr:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.11/site-packages/kivy/uix/behaviors/button.py", line 121, in __init__
[WARNING] stderr:     super(ButtonBehavior, self).__init__(**kwargs)
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.11/site-packages/kivy/uix/label.py", line 318, in __init__
[WARNING] stderr:     super(Label, self).__init__(**kwargs)
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.11/site-packages/kivy/uix/widget.py", line 357, in __init__
[WARNING] stderr:     super(Widget, self).__init__(**kwargs)
[WARNING] stderr:   File "kivy/_event.pyx", line 262, in kivy._event.EventDispatcher.__init__
[WARNING] stderr:   File "kivy/properties.pyx", line 520, in kivy.properties.Property.__set__
[WARNING] stderr:   File "kivy/properties.pyx", line 549, in kivy.properties.Property.set
[WARNING] stderr:   File "kivy/properties.pyx", line 2232, in kivy.properties.ColorProperty.convert
[WARNING] stderr: ValueError: Button.background_color has an invalid format (got 'Red')
